# Generated by Django 4.2.30 on 2026-06-13 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shipments', '0004_shipment_estimated_revenue_shipment_is_verified_and_more'),
        ('fleet', '0002_driver_fuel_efficiency_rating_driver_license_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('ACCEPTED', 'Accepted'), ('DISPATCHED', 'Dispatched'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PROPOSED', max_length=20)),
                ('compatibility_score', models.DecimalField(decimal_places=2, default=0, help_text='Overall weighted compatibility score (0-100)', max_digits=5)),
                ('route_experience_score', models.DecimalField(decimal_places=2, default=0, help_text='Score based on past trips on same route (30% weight)', max_digits=5)),
                ('proximity_score', models.DecimalField(decimal_places=2, default=0, help_text='Score based on distance to pickup (25% weight)', max_digits=5)),
                ('vehicle_match_score', models.DecimalField(decimal_places=2, default=0, help_text='Score based on truck type + capacity match (20% weight)', max_digits=5)),
                ('driver_rating_score', models.DecimalField(decimal_places=2, default=0, help_text='Score based on driver performance rating (15% weight)', max_digits=5)),
                ('fuel_efficiency_score', models.DecimalField(decimal_places=2, default=0, help_text='Score based on fuel efficiency (10% weight)', max_digits=5)),
                ('notes', models.TextField(blank=True, default='')),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='fleet.driver')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='shipments.shipment')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='fleet.truck')),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['shipment', 'status'], name='assignments_shipmen_491b02_idx'), models.Index(fields=['driver', 'status'], name='assignments_driver__4228d2_idx')],
            },
        ),
    ]
