# Generated by Django 4.2.30 on 2026-06-13 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shipments', '0004_shipment_estimated_revenue_shipment_is_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProofOfDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver_name', models.CharField(help_text='Name of the person receiving the delivery', max_length=255)),
                ('receiver_phone', models.CharField(blank=True, default='', max_length=15)),
                ('otp_code', models.CharField(help_text='OTP sent to receiver for verification', max_length=6)),
                ('otp_verified', models.BooleanField(default=False)),
                ('otp_verified_at', models.DateTimeField(blank=True, null=True)),
                ('signature_image', models.ImageField(blank=True, help_text='Digital signature of the receiver', null=True, upload_to='pod_signatures/')),
                ('cargo_images', models.JSONField(default=list, help_text='List of image paths for cargo photographs')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude at PoD submission', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude at PoD submission', max_digits=9, null=True)),
                ('geofence_valid', models.BooleanField(default=False, help_text='Whether GPS location was within the assigned dock geofence')),
                ('notes', models.TextField(blank=True, default='')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proof_of_delivery', to='shipments.shipment')),
            ],
            options={
                'verbose_name': 'Proof of Delivery',
                'verbose_name_plural': 'Proofs of Delivery',
                'ordering': ['-created_at'],
            },
        ),
    ]
