# Generated by Django 4.2.30 on 2026-06-13 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0003_organization_company_type_organization_is_verified_and_more'),
        ('shipments', '0004_shipment_estimated_revenue_shipment_is_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('origin_name', models.CharField(max_length=255)),
                ('destination_name', models.CharField(max_length=255)),
                ('origin_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('origin_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('dest_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('dest_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('cargo_type', models.CharField(max_length=100)),
                ('weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rate_per_km', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('estimated_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('load_type', models.CharField(choices=[('TIE_UP', 'Tie-Up Factory'), ('OPEN_MARKET', 'Open Market')], default='OPEN_MARKET', max_length=20)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('LOCKED', 'Locked'), ('ACCEPTED', 'Accepted'), ('EXPIRED', 'Expired')], default='AVAILABLE', max_length=20)),
                ('vehicle_type_required', models.CharField(blank=True, default='', max_length=50)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_loads', to='organizations.organization')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_loads', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_load', to='shipments.shipment')),
            ],
            options={
                'verbose_name': 'Marketplace Load',
                'verbose_name_plural': 'Marketplace Loads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_accepted', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('bid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placed_bids', to=settings.AUTH_USER_MODEL)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_bids', to='organizations.organization')),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='marketplace.marketplaceload')),
            ],
            options={
                'verbose_name': 'Marketplace Bid',
                'verbose_name_plural': 'Marketplace Bids',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='marketplaceload',
            index=models.Index(fields=['status', 'load_type'], name='marketplace_status_9c9000_idx'),
        ),
    ]
