# Generated by Django 4.2.30 on 2026-06-11 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SHIPMENT_CREATED', 'Shipment Created'), ('SHIPMENT_UPDATED', 'Shipment Updated'), ('TRUCK_ASSIGNED', 'Truck Assigned'), ('TRUCK_UNASSIGNED', 'Truck Unassigned'), ('DRIVER_ASSIGNED', 'Driver Assigned'), ('DRIVER_UNASSIGNED', 'Driver Unassigned'), ('DOCK_RESERVED', 'Dock Reserved'), ('DOCK_RELEASED', 'Dock Released'), ('DISPATCH_APPROVED', 'Dispatch Approved'), ('SHIPMENT_ARRIVED', 'Shipment Arrived'), ('UNLOADING_STARTED', 'Unloading Started'), ('SHIPMENT_COMPLETED', 'Shipment Completed'), ('SHIPMENT_CANCELLED', 'Shipment Cancelled')], max_length=30)),
                ('resource_type', models.CharField(help_text='Model name, e.g. Shipment, Truck, DockReservation', max_length=50)),
                ('resource_id', models.PositiveIntegerField()),
                ('previous_state', models.JSONField(blank=True, default=dict)),
                ('new_state', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
