# Generated by Django 4.2.30 on 2026-06-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('SHIPMENT_CREATED', 'Shipment Created'), ('SHIPMENT_UPDATED', 'Shipment Updated'), ('TRUCK_ASSIGNED', 'Truck Assigned'), ('TRUCK_UNASSIGNED', 'Truck Unassigned'), ('DRIVER_ASSIGNED', 'Driver Assigned'), ('DRIVER_UNASSIGNED', 'Driver Unassigned'), ('DOCK_RESERVED', 'Dock Reserved'), ('DOCK_RELEASED', 'Dock Released'), ('DISPATCH_APPROVED', 'Dispatch Approved'), ('SHIPMENT_ARRIVED', 'Shipment Arrived'), ('UNLOADING_STARTED', 'Unloading Started'), ('SHIPMENT_COMPLETED', 'Shipment Completed'), ('SHIPMENT_CANCELLED', 'Shipment Cancelled'), ('TELEMETRY_RECEIVED', 'Telemetry Received'), ('GEOFENCE_TRIGGERED', 'Geofence Triggered'), ('RETURN_LOAD_ACCEPTED', 'Return Load Accepted'), ('DOCK_SWAP_APPROVED', 'Dock Swap Approved')], max_length=30),
        ),
    ]
