# Generated by Django 4.2.30 on 2026-06-12 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shipments', '0002_alter_shipment_status'),
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('speed', models.DecimalField(decimal_places=2, default=0, help_text='Speed in km/h', max_digits=6)),
                ('heading', models.DecimalField(decimal_places=2, default=0, help_text='Compass heading in degrees (0-360)', max_digits=5)),
                ('battery_level', models.PositiveSmallIntegerField(default=100, help_text='Device battery percentage (0-100)')),
                ('recorded_at', models.DateTimeField(help_text='Timestamp from the device when this reading was taken')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_points', to='fleet.driver')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telemetry_points', to='shipments.shipment')),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telemetry_points', to='fleet.truck')),
            ],
            options={
                'verbose_name': 'Telemetry Point',
                'verbose_name_plural': 'Telemetry Points',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['driver', '-recorded_at'], name='telemetry_t_driver__0c88bf_idx'), models.Index(fields=['truck', '-recorded_at'], name='telemetry_t_truck_i_4c9d94_idx'), models.Index(fields=['shipment', '-recorded_at'], name='telemetry_t_shipmen_576771_idx'), models.Index(fields=['-recorded_at'], name='telemetry_t_recorde_8106ad_idx')],
            },
        ),
    ]
