# Generated by Django 4.2.30 on 2026-06-12 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rack_id', models.CharField(help_text='Display ID, e.g. R-01', max_length=20)),
                ('row_index', models.PositiveIntegerField(default=0)),
                ('col_index', models.PositiveIntegerField(default=0)),
                ('x_position', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('z_position', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('num_shelves', models.PositiveIntegerField(default=4)),
                ('shelf_width', models.DecimalField(decimal_places=2, default=3.0, help_text='Width of each shelf in meters.', max_digits=6)),
                ('shelf_depth', models.DecimalField(decimal_places=2, default=1.5, help_text='Depth of each shelf in meters.', max_digits=6)),
                ('shelf_height', models.DecimalField(decimal_places=2, default=1.0, help_text='Height of each shelf in meters.', max_digits=6)),
            ],
            options={
                'verbose_name': 'Rack',
                'verbose_name_plural': 'Racks',
                'ordering': ['rack_id'],
            },
        ),
        migrations.AddField(
            model_name='dockbay',
            name='x_position',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='X coordinate in warehouse 3D space.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='dockbay',
            name='z_position',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Z coordinate in warehouse 3D space.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='depth',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Warehouse depth in meters.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Warehouse wall height in meters.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='layout_version',
            field=models.PositiveIntegerField(default=1, help_text='Version number for layout tracking.'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Warehouse width in meters.', max_digits=8, null=True),
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.PositiveIntegerField(help_text='Shelf level (1=bottom, N=top).')),
                ('available_volume', models.DecimalField(decimal_places=2, default=0, help_text='Remaining volume in cubic meters.', max_digits=10)),
                ('occupied_volume', models.DecimalField(decimal_places=2, default=0, help_text='Used volume in cubic meters.', max_digits=10)),
                ('max_weight', models.DecimalField(decimal_places=2, default=500, help_text='Maximum weight capacity in kg.', max_digits=8)),
                ('current_weight', models.DecimalField(decimal_places=2, default=0, help_text='Current weight on shelf in kg.', max_digits=8)),
                ('is_locked', models.BooleanField(default=False, help_text='Locked by manager — no automatic placement.')),
                ('is_reserved', models.BooleanField(default=False, help_text='Reserved for specific incoming parcel.')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to='warehouses.rack')),
            ],
            options={
                'verbose_name': 'Shelf',
                'verbose_name_plural': 'Shelves',
                'ordering': ['rack', 'level'],
                'unique_together': {('rack', 'level')},
            },
        ),
        migrations.AddField(
            model_name='rack',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='warehouses.warehouse'),
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parcel_id', models.CharField(help_text='Unique parcel identifier, e.g. PKG-A4F2B1.', max_length=30, unique=True)),
                ('height', models.DecimalField(decimal_places=2, help_text='Height in meters.', max_digits=6)),
                ('width', models.DecimalField(decimal_places=2, help_text='Width in meters.', max_digits=6)),
                ('depth', models.DecimalField(decimal_places=2, help_text='Depth in meters.', max_digits=6)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kg.', max_digits=8)),
                ('destination', models.CharField(max_length=255)),
                ('expected_dispatch_date', models.DateField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('special_handling', models.TextField(blank=True, default='')),
                ('position_label', models.CharField(blank=True, default='', help_text='Compartment position on shelf, e.g. A2.', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('STORED', 'Stored'), ('DISPATCHED', 'Dispatched')], default='PENDING', max_length=20)),
                ('shelf', models.ForeignKey(blank=True, help_text='Assigned shelf (null if pending placement).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcels', to='warehouses.shelf')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='warehouses.warehouse')),
            ],
            options={
                'verbose_name': 'Parcel',
                'verbose_name_plural': 'Parcels',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='rack',
            unique_together={('warehouse', 'rack_id')},
        ),
    ]
