# Generated by Django 4.2.30 on 2026-06-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0002_rack_dockbay_x_position_dockbay_z_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='color',
            field=models.CharField(default='#C28E5F', max_length=7),
        ),
    ]
