# Generated by Django 4.2.30 on 2026-06-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0003_parcel_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='destination',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='parcel',
            name='status',
            field=models.CharField(default='STORED', max_length=50),
        ),
    ]
