# Generated by Django 4.2.30 on 2026-06-13 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0004_parcel_destination_parcel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='layout_depth',
            field=models.FloatField(default=30.0),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='layout_height',
            field=models.FloatField(default=6.0),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='layout_width',
            field=models.FloatField(default=50.0),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='max_concurrent_trucks',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='operating_hours',
            field=models.CharField(blank=True, default='24/7', max_length=255),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='special_handling',
            field=models.JSONField(blank=True, default=list, help_text='List of capabilities like "Temperature Controlled", "Hazardous Goods"'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='warehouse_type',
            field=models.CharField(choices=[('DESTINATION_WAREHOUSE', 'Destination Warehouse'), ('TRANSIT_WAREHOUSE', 'Transit Warehouse'), ('DISTRIBUTION_CENTER', 'Distribution Center')], default='DESTINATION_WAREHOUSE', max_length=50),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='expected_dispatch_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='parcel_id',
            field=models.CharField(help_text='Unique parcel identifier, e.g. PKG-A4F2B1.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('STORED', 'Stored'), ('DISPATCHED', 'Dispatched')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='warehouses.warehouse'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Weight in kg.', max_digits=8),
        ),
        migrations.AlterField(
            model_name='rack',
            name='rack_id',
            field=models.CharField(help_text='Display ID, e.g. R-01', max_length=50),
        ),
    ]
