# Generated by Django 4.2.30 on 2026-06-11 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shipments', '0002_alter_shipment_status'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('SHIPMENT_CREATED', 'Shipment Created'), ('TRUCK_ASSIGNED', 'Truck Assigned'), ('TRUCK_UNASSIGNED', 'Truck Unassigned'), ('DRIVER_ASSIGNED', 'Driver Assigned'), ('DRIVER_UNASSIGNED', 'Driver Unassigned'), ('DOCK_RESERVED', 'Dock Reserved'), ('DISPATCHED', 'Dispatched'), ('ARRIVED', 'Arrived'), ('DOCK_ENTERED', 'Dock Entered'), ('UNLOADING_STARTED', 'Unloading Started'), ('UNLOADING_COMPLETED', 'Unloading Completed'), ('SHIPMENT_COMPLETED', 'Shipment Completed'), ('CANCELLED', 'Cancelled'), ('STATUS_CHANGED', 'Status Changed')], max_length=25)),
                ('description', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_events', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='shipments.shipment')),
            ],
            options={
                'verbose_name': 'Shipment Event',
                'verbose_name_plural': 'Shipment Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('reservation_status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=15)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('dock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='warehouses.dockbay')),
                ('reserved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dock_reservations', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dock_reservations', to='shipments.shipment')),
            ],
            options={
                'verbose_name': 'Dock Reservation',
                'verbose_name_plural': 'Dock Reservations',
                'ordering': ['-reserved_at'],
            },
        ),
    ]
