# Generated by Django 4.2.30 on 2026-06-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentevent',
            name='event_type',
            field=models.CharField(choices=[('SHIPMENT_CREATED', 'Shipment Created'), ('TRUCK_ASSIGNED', 'Truck Assigned'), ('TRUCK_UNASSIGNED', 'Truck Unassigned'), ('DRIVER_ASSIGNED', 'Driver Assigned'), ('DRIVER_UNASSIGNED', 'Driver Unassigned'), ('DOCK_RESERVED', 'Dock Reserved'), ('DISPATCHED', 'Dispatched'), ('ARRIVED', 'Arrived'), ('DOCK_ENTERED', 'Dock Entered'), ('UNLOADING_STARTED', 'Unloading Started'), ('UNLOADING_COMPLETED', 'Unloading Completed'), ('SHIPMENT_COMPLETED', 'Shipment Completed'), ('CANCELLED', 'Cancelled'), ('STATUS_CHANGED', 'Status Changed'), ('GEOFENCE_ENTERED', 'Geofence Entered'), ('GEOFENCE_EXITED', 'Geofence Exited'), ('ETA_UPDATED', 'ETA Updated'), ('RETURN_LOAD_MATCHED', 'Return Load Matched'), ('RETURN_LOAD_ACCEPTED', 'Return Load Accepted'), ('DELAY_DETECTED', 'Delay Detected')], max_length=25),
        ),
    ]
