# Generated by Django 4.2.30 on 2026-06-13 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0003_organization_company_type_organization_is_verified_and_more'),
        ('operations', '0002_alter_shipmentevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentevent',
            name='event_type',
            field=models.CharField(choices=[('SHIPMENT_CREATED', 'Shipment Created'), ('TRUCK_ASSIGNED', 'Truck Assigned'), ('TRUCK_UNASSIGNED', 'Truck Unassigned'), ('DRIVER_ASSIGNED', 'Driver Assigned'), ('DRIVER_UNASSIGNED', 'Driver Unassigned'), ('DOCK_RESERVED', 'Dock Reserved'), ('DISPATCHED', 'Dispatched'), ('ARRIVED', 'Arrived'), ('DOCK_ENTERED', 'Dock Entered'), ('UNLOADING_STARTED', 'Unloading Started'), ('UNLOADING_COMPLETED', 'Unloading Completed'), ('SHIPMENT_COMPLETED', 'Shipment Completed'), ('CANCELLED', 'Cancelled'), ('STATUS_CHANGED', 'Status Changed'), ('GEOFENCE_ENTERED', 'Geofence Entered'), ('GEOFENCE_EXITED', 'Geofence Exited'), ('ETA_UPDATED', 'ETA Updated'), ('RETURN_LOAD_MATCHED', 'Return Load Matched'), ('RETURN_LOAD_ACCEPTED', 'Return Load Accepted'), ('DELAY_DETECTED', 'Delay Detected'), ('LOADING_VERIFIED', 'Loading Verified'), ('MILESTONE_CONFIRMED', 'Milestone Confirmed'), ('POD_SUBMITTED', 'PoD Submitted'), ('DELAY_REPORTED', 'Delay Reported'), ('ASSIGNMENT_CREATED', 'Assignment Created'), ('ASSIGNMENT_ACCEPTED', 'Assignment Accepted'), ('CHAT_ESCALATION', 'Chat Escalation')], max_length=25),
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.CharField(blank=True, default='OPERATIONS', max_length=100)),
                ('operational_role', models.CharField(blank=True, default='STAFF', max_length=100)),
                ('shift_type', models.CharField(blank=True, default='DAY', max_length=50)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='organizations.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Profile',
                'verbose_name_plural': 'Employee Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
