# Generated by Django 4.2.30 on 2026-06-14 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shipments', '0005_alter_shipment_status'),
        ('operations', '0003_alter_shipmentevent_event_type_employeeprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentevent',
            name='event_type',
            field=models.CharField(choices=[('SHIPMENT_CREATED', 'Shipment Created'), ('TRUCK_ASSIGNED', 'Truck Assigned'), ('TRUCK_UNASSIGNED', 'Truck Unassigned'), ('DRIVER_ASSIGNED', 'Driver Assigned'), ('DRIVER_UNASSIGNED', 'Driver Unassigned'), ('DOCK_RESERVED', 'Dock Reserved'), ('DISPATCHED', 'Dispatched'), ('ARRIVED', 'Arrived'), ('DOCK_ENTERED', 'Dock Entered'), ('UNLOADING_STARTED', 'Unloading Started'), ('UNLOADING_COMPLETED', 'Unloading Completed'), ('SHIPMENT_COMPLETED', 'Shipment Completed'), ('CANCELLED', 'Cancelled'), ('STATUS_CHANGED', 'Status Changed'), ('GEOFENCE_ENTERED', 'Geofence Entered'), ('GEOFENCE_EXITED', 'Geofence Exited'), ('ETA_UPDATED', 'ETA Updated'), ('RETURN_LOAD_MATCHED', 'Return Load Matched'), ('RETURN_LOAD_ACCEPTED', 'Return Load Accepted'), ('DELAY_DETECTED', 'Delay Detected'), ('LOADING_VERIFIED', 'Loading Verified'), ('MILESTONE_CONFIRMED', 'Milestone Confirmed'), ('POD_SUBMITTED', 'PoD Submitted'), ('DELAY_REPORTED', 'Delay Reported'), ('ASSIGNMENT_CREATED', 'Assignment Created'), ('ASSIGNMENT_ACCEPTED', 'Assignment Accepted'), ('CHAT_ESCALATION', 'Chat Escalation'), ('GATE_CHECK_IN', 'Gate Check-In'), ('RECEIVING_STARTED', 'Receiving Started'), ('RECEIVING_COMPLETED', 'Receiving Completed'), ('EXCEPTION_RAISED', 'Exception Raised')], max_length=25),
        ),
        migrations.CreateModel(
            name='GateCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('truck_number', models.CharField(blank=True, max_length=50)),
                ('driver_name', models.CharField(blank=True, max_length=100)),
                ('seal_number', models.CharField(blank=True, max_length=100)),
                ('documents_verified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gate_check_in', to='shipments.shipment')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_check_ins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gate Check-In',
                'verbose_name_plural': 'Gate Check-Ins',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExceptionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exception_type', models.CharField(choices=[('MISSING_PARCEL', 'Missing Parcel'), ('DAMAGED_GOODS', 'Damaged Goods'), ('WRONG_QUANTITY', 'Wrong Quantity'), ('BROKEN_SEAL', 'Broken Seal'), ('INCORRECT_DOCS', 'Incorrect Documentation'), ('OTHER', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='exceptions/')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVING', 'Resolving'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20)),
                ('resolution_notes', models.TextField(blank=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_exceptions', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exception_reports', to='shipments.shipment')),
            ],
            options={
                'verbose_name': 'Exception Report',
                'verbose_name_plural': 'Exception Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
