# Generated by Django 4.2.30 on 2026-06-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='User profile photo', null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_phone_verified',
            field=models.BooleanField(default=False, help_text='Whether phone number has been verified via OTP'),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', help_text='KYC verification status', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('FACTORY_MANAGER', 'Factory Manager'), ('WAREHOUSE_MANAGER', 'Warehouse Manager'), ('DRIVER', 'Driver'), ('ADMIN', 'Admin'), ('EMPLOYEE', 'Employee')], default='DRIVER', max_length=30),
        ),
    ]
