# Generated by Django 4.2.30 on 2026-06-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_avatar_user_is_phone_verified_user_kyc_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='requires_password_change',
            field=models.BooleanField(default=False, help_text='Forces the user to change their password on first login (for provisioned accounts)'),
        ),
    ]
