# Generated by Django 4.2.30 on 2026-06-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_requires_password_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('FACTORY_MANAGER', 'Factory Manager'), ('WAREHOUSE_MANAGER', 'Warehouse Manager'), ('DRIVER', 'Driver'), ('ADMIN', 'Admin'), ('EMPLOYEE', 'Employee'), ('DISPATCH_MANAGER', 'Dispatch Manager'), ('OPERATIONS_MANAGER', 'Operations Manager'), ('INVENTORY_MANAGER', 'Inventory Manager'), ('FINANCE_MANAGER', 'Finance Manager'), ('READ_ONLY', 'Read Only User')], default='DRIVER', max_length=30),
        ),
    ]
