# Generated by Django 4.2.30 on 2026-06-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('FACTORY', 'Factory'), ('WAREHOUSE', 'Warehouse'), ('LOGISTICS_PROVIDER', 'Logistics Provider')], default='FACTORY', max_length=50),
        ),
    ]
