# Generated by Django 4.2.30 on 2026-06-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_org_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='company_type',
            field=models.CharField(blank=True, default='', help_text='Type of company (e.g., Logistics, Transport, Fleet)', max_length=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether the company has been verified by platform admin'),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='pan_number',
            field=models.CharField(blank=True, default='', help_text='10-character PAN number', max_length=10),
        ),
    ]
