# Generated by Django 4.2.30 on 2026-06-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_company_type_organization_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Flexible schema for org-specific details (e.g. logistics fleet data)'),
        ),
    ]
