# Generated by Django 4.2.30 on 2026-06-13 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shipments', '0004_shipment_estimated_revenue_shipment_is_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelayEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delay_type', models.CharField(choices=[('TRAFFIC', 'Traffic'), ('FLAT_TIRE', 'Flat Tire'), ('POLICE_CHECKPOINT', 'Police Checkpoint'), ('WEATHER', 'Weather'), ('MECHANICAL', 'Mechanical Issue'), ('OTHER', 'Other')], max_length=30)),
                ('estimated_delay_minutes', models.PositiveIntegerField(help_text='Estimated delay in minutes')),
                ('description', models.TextField(blank=True, default='', help_text='Additional details about the delay')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_delays', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delay_events', to='shipments.shipment')),
            ],
            options={
                'verbose_name': 'Delay Event',
                'verbose_name_plural': 'Delay Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('milestone_type', models.CharField(choices=[('ARRIVED_FACTORY', 'Arrived at Factory'), ('LOADING_COMPLETE', 'Loading Completed'), ('LOADING_VERIFIED', 'Loading Verified'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED_DESTINATION', 'Arrived at Destination'), ('POD_SUBMITTED', 'PoD Submitted')], max_length=30)),
                ('sequence', models.PositiveSmallIntegerField(default=0, help_text='Order in which this milestone appears (0-based)')),
                ('is_confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude at confirmation', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude at confirmation', max_digits=9, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_milestones', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='shipments.shipment')),
            ],
            options={
                'verbose_name': 'Milestone',
                'verbose_name_plural': 'Milestones',
                'ordering': ['shipment', 'sequence'],
                'unique_together': {('shipment', 'milestone_type')},
            },
        ),
    ]
