# Generated by Django 4.2.30 on 2026-06-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('SHIPMENT', 'Shipment'), ('ASSIGNMENT', 'Assignment'), ('DOCK', 'Dock'), ('SYSTEM', 'System'), ('ALERT', 'Alert'), ('TELEMETRY', 'Telemetry'), ('GEOFENCE', 'Geofence'), ('RETURN_LOAD', 'Return Load')], default='SYSTEM', max_length=15),
        ),
    ]
