# Generated by Django 4.2.30 on 2026-06-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('SHIPMENT', 'Shipment'), ('ASSIGNMENT', 'Assignment'), ('DOCK', 'Dock'), ('SYSTEM', 'System'), ('ALERT', 'Alert'), ('TELEMETRY', 'Telemetry'), ('GEOFENCE', 'Geofence'), ('RETURN_LOAD', 'Return Load'), ('CHAT', 'Chat'), ('MILESTONE', 'Milestone'), ('VERIFICATION', 'Verification'), ('KYC', 'KYC'), ('POD', 'Proof of Delivery')], default='SYSTEM', max_length=15),
        ),
    ]
