# Generated by Django 4.2.30 on 2026-06-12 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_from_logistics', models.BooleanField(default=False)),
                ('text', models.TextField()),
                ('attachment_url', models.URLField(blank=True, null=True)),
                ('read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='factories.factory')),
            ],
        ),
        migrations.CreateModel(
            name='LogisticsCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('fleet_size', models.PositiveIntegerField(default=10)),
                ('coverage_regions', models.JSONField(default=list, help_text='List of regions/states covered')),
                ('average_response_time_mins', models.PositiveIntegerField(default=30)),
                ('completed_jobs', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Logistics Companies',
                'ordering': ['-rating', '-completed_jobs'],
            },
        ),
        migrations.CreateModel(
            name='LotQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('estimated_delivery_hours', models.PositiveIntegerField()),
                ('number_of_vehicles', models.PositiveIntegerField(default=1)),
                ('special_conditions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('REVISION_REQUESTED', 'Revision Requested')], default='PENDING', max_length=20)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='logistics.chatroom')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='chatroom',
            name='logistics_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='logistics.logisticscompany'),
        ),
    ]
