from django.db import models
from django.conf import settings
from common.models import TimestampMixin
from common.enums import ReturnLoadStatus, RecommendationType, RecommendationStatus


class ETAPrediction(models.Model):
    """
    Predicted arrival time for a shipment, generated from telemetry data.
    Multiple predictions may exist per shipment as the truck moves.
    """
    shipment = models.ForeignKey(
        'shipments.Shipment',
        on_delete=models.CASCADE,
        related_name='eta_predictions',
    )
    predicted_eta = models.DateTimeField()
    confidence = models.DecimalField(
        max_digits=5, decimal_places=2, default=0.80,
        help_text='Confidence score (0.00 - 1.00)',
    )
    delay_probability = models.DecimalField(
        max_digits=5, decimal_places=2, default=0.00,
        help_text='Probability of delay (0.00 - 1.00)',
    )
    remaining_distance_km = models.DecimalField(
        max_digits=8, decimal_places=2, null=True, blank=True,
    )
    generated_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-generated_at']
        verbose_name = 'ETA Prediction'
        verbose_name_plural = 'ETA Predictions'

    def __str__(self):
        return f"ETA for {self.shipment.shipment_number}: {self.predicted_eta}"


class DockRecommendation(TimestampMixin, models.Model):
    """
    Dock optimization recommendations generated by the intelligence engine.
    Includes dock swaps, assignments, and delay alerts.
    """
    warehouse = models.ForeignKey(
        'warehouses.Warehouse',
        on_delete=models.CASCADE,
        related_name='dock_recommendations',
    )
    recommendation_type = models.CharField(
        max_length=20,
        choices=RecommendationType.choices,
    )
    affected_shipments = models.JSONField(
        default=list,
        help_text='List of shipment IDs affected by this recommendation',
    )
    reason = models.TextField()
    status = models.CharField(
        max_length=15,
        choices=RecommendationStatus.choices,
        default=RecommendationStatus.PENDING,
    )
    resolved_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True, blank=True,
        related_name='resolved_recommendations',
    )
    resolved_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Dock Recommendation'
        verbose_name_plural = 'Dock Recommendations'

    def __str__(self):
        return f"{self.get_recommendation_type_display()} @ {self.warehouse.name}"


class ReturnLoad(TimestampMixin, models.Model):
    """
    A return-load match — links a completing/completed truck
    with a nearby outbound shipment to reduce empty miles.
    """
    # The original shipment the truck is delivering/delivered
    original_shipment = models.ForeignKey(
        'shipments.Shipment',
        on_delete=models.CASCADE,
        related_name='return_load_opportunities',
    )
    # The potential return shipment
    return_shipment = models.ForeignKey(
        'shipments.Shipment',
        on_delete=models.CASCADE,
        related_name='return_load_matches',
    )
    truck = models.ForeignKey(
        'fleet.Truck',
        on_delete=models.CASCADE,
        related_name='return_load_matches',
    )
    driver = models.ForeignKey(
        'fleet.Driver',
        on_delete=models.CASCADE,
        related_name='return_load_matches',
    )
    match_score = models.DecimalField(
        max_digits=5, decimal_places=2, default=0,
        help_text='Compatibility score (0-100)',
    )
    distance_to_pickup = models.DecimalField(
        max_digits=8, decimal_places=2, default=0,
        help_text='Distance in km to the return load pickup point',
    )
    estimated_revenue = models.DecimalField(
        max_digits=12, decimal_places=2, default=0,
    )
    status = models.CharField(
        max_length=15,
        choices=ReturnLoadStatus.choices,
        default=ReturnLoadStatus.SUGGESTED,
    )

    class Meta:
        ordering = ['-match_score']
        verbose_name = 'Return Load'
        verbose_name_plural = 'Return Loads'

    def __str__(self):
        return (
            f"Return load: {self.truck.registration_number} → "
            f"{self.return_shipment.shipment_number} (score: {self.match_score})"
        )
