# Generated by Django 4.2.30 on 2026-06-12 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shipments', '0002_alter_shipment_status'),
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_score', models.DecimalField(decimal_places=2, default=0, help_text='Compatibility score (0-100)', max_digits=5)),
                ('distance_to_pickup', models.DecimalField(decimal_places=2, default=0, help_text='Distance in km to the return load pickup point', max_digits=8)),
                ('estimated_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('SUGGESTED', 'Suggested'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('COMPLETED', 'Completed')], default='SUGGESTED', max_length=15)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_load_matches', to='fleet.driver')),
                ('original_shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_load_opportunities', to='shipments.shipment')),
                ('return_shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_load_matches', to='shipments.shipment')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_load_matches', to='fleet.truck')),
            ],
            options={
                'verbose_name': 'Return Load',
                'verbose_name_plural': 'Return Loads',
                'ordering': ['-match_score'],
            },
        ),
        migrations.CreateModel(
            name='ETAPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_eta', models.DateTimeField()),
                ('confidence', models.DecimalField(decimal_places=2, default=0.8, help_text='Confidence score (0.00 - 1.00)', max_digits=5)),
                ('delay_probability', models.DecimalField(decimal_places=2, default=0.0, help_text='Probability of delay (0.00 - 1.00)', max_digits=5)),
                ('remaining_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eta_predictions', to='shipments.shipment')),
            ],
            options={
                'verbose_name': 'ETA Prediction',
                'verbose_name_plural': 'ETA Predictions',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='DockRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommendation_type', models.CharField(choices=[('DOCK_SWAP', 'Dock Swap'), ('DOCK_ASSIGNMENT', 'Dock Assignment'), ('DELAY_ALERT', 'Delay Alert')], max_length=20)),
                ('affected_shipments', models.JSONField(default=list, help_text='List of shipment IDs affected by this recommendation')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_recommendations', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dock_recommendations', to='warehouses.warehouse')),
            ],
            options={
                'verbose_name': 'Dock Recommendation',
                'verbose_name_plural': 'Dock Recommendations',
                'ordering': ['-created_at'],
            },
        ),
    ]
