# Generated by Django 4.2.30 on 2026-06-11 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shipments.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('factories', '0001_initial'),
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment_number', models.CharField(default=shipments.models.generate_shipment_number, editable=False, max_length=20, unique=True)),
                ('shipment_type', models.CharField(choices=[('RAW_MATERIAL', 'Raw Material'), ('FINISHED_GOODS', 'Finished Goods'), ('RETURN_LOAD', 'Return Load')], default='FINISHED_GOODS', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('ASSIGNED', 'Assigned'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED', 'Arrived'), ('UNLOADING', 'Unloading'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=20)),
                ('expected_dispatch_time', models.DateTimeField(blank=True, null=True)),
                ('expected_arrival_time', models.DateTimeField(blank=True, null=True)),
                ('actual_dispatch_time', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival_time', models.DateTimeField(blank=True, null=True)),
                ('assigned_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='fleet.driver')),
                ('assigned_truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='fleet.truck')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shipments', to=settings.AUTH_USER_MODEL)),
                ('destination_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_shipments', to='warehouses.warehouse')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='factories.factory')),
            ],
            options={
                'verbose_name': 'Shipment',
                'verbose_name_plural': 'Shipments',
                'ordering': ['-created_at'],
            },
        ),
    ]
