# Generated by Django 4.2.30 on 2026-06-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('READY_FOR_ASSIGNMENT', 'Ready for Assignment'), ('TRUCK_ASSIGNED', 'Truck Assigned'), ('DRIVER_ASSIGNED', 'Driver Assigned'), ('DOCK_RESERVED', 'Dock Reserved'), ('READY_FOR_DISPATCH', 'Ready for Dispatch'), ('DISPATCHED', 'Dispatched'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED_AT_WAREHOUSE', 'Arrived at Warehouse'), ('WAITING_FOR_DOCK', 'Waiting for Dock'), ('DOCK_ASSIGNED', 'Dock Assigned'), ('UNLOADING', 'Unloading'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='CREATED', max_length=25),
        ),
    ]
