# Generated by Django 4.2.30 on 2026-06-12 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shipments.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistics', '0001_initial'),
        ('warehouses', '0002_rack_dockbay_x_position_dockbay_z_position_and_more'),
        ('factories', '0001_initial'),
        ('shipments', '0002_alter_shipment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lot_number', models.CharField(default=shipments.models.generate_lot_number, editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('UNDER_REVIEW', 'Under Review'), ('SHARED', 'Shared with Logistics'), ('ACCEPTED', 'Accepted Quote'), ('SHIPMENT_GENERATED', 'Shipment Generated'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=25)),
                ('expected_dispatch_date', models.DateField(blank=True, null=True)),
                ('assigned_logistics_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_lots', to='logistics.logisticscompany')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('destination_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_lots', to='warehouses.warehouse')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='factories.factory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LotParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parcel_id', models.CharField(max_length=50)),
                ('length', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('width', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('height', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('dispatch_priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('is_fragile', models.BooleanField(default=False)),
                ('temperature_requirement', models.CharField(blank=True, max_length=100)),
                ('insurance_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='shipments.lot')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='shipment',
            name='lot',
            field=models.ForeignKey(blank=True, help_text='The negotiated lot from which this shipment was generated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='shipments.lot'),
        ),
    ]
