# Generated by Django 4.2.30 on 2026-06-13 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_company_type_organization_is_verified_and_more'),
        ('shipments', '0003_lot_lotparcel_shipment_lot'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='estimated_revenue',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Estimated revenue for the shipment', max_digits=12),
        ),
        migrations.AddField(
            model_name='shipment',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether loading has been verified by employee'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='logistics_provider',
            field=models.ForeignKey(blank=True, help_text='The logistics company handling this shipment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_shipments', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='pod_submitted',
            field=models.BooleanField(default=False, help_text='Whether proof of delivery has been submitted'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='total_distance_km',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total route distance in km', max_digits=10),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('READY_FOR_ASSIGNMENT', 'Ready for Assignment'), ('TRUCK_ASSIGNED', 'Truck Assigned'), ('DRIVER_ASSIGNED', 'Driver Assigned'), ('DOCK_RESERVED', 'Dock Reserved'), ('READY_FOR_DISPATCH', 'Ready for Dispatch'), ('DISPATCHED', 'Dispatched'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED_AT_WAREHOUSE', 'Arrived at Warehouse'), ('WAITING_FOR_DOCK', 'Waiting for Dock'), ('DOCK_ASSIGNED', 'Dock Assigned'), ('UNLOADING', 'Unloading'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed'), ('LOADING_VERIFIED', 'Loading Verified'), ('POD_SUBMITTED', 'PoD Submitted')], default='CREATED', max_length=25),
        ),
    ]
