# Generated by Django 4.2.30 on 2026-06-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0004_shipment_estimated_revenue_shipment_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('WAREHOUSE_APPROVED', 'Warehouse Approved'), ('LOGISTICS_SELECTED', 'Logistics Selected'), ('DRIVER_ASSIGNED', 'Driver Assigned'), ('READY_FOR_PICKUP', 'Ready for Pickup'), ('LOADING_IN_PROGRESS', 'Loading In Progress'), ('READY_FOR_TRANSIT', 'Ready for Transit'), ('IN_TRANSIT', 'In Transit'), ('APPROACHING_DESTINATION', 'Approaching Destination'), ('ARRIVED_AT_GATE', 'Arrived at Gate'), ('RECEIVING_IN_PROGRESS', 'Receiving In Progress'), ('SLOTTING_IN_PROGRESS', 'Slotting In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='DRAFT', max_length=25),
        ),
    ]
