# Generated by Django 4.2.30 on 2026-06-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_alter_shipment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_WAREHOUSE_APPROVAL', 'Pending Warehouse Approval'), ('WAREHOUSE_APPROVED', 'Warehouse Approved'), ('WAREHOUSE_REJECTED', 'Warehouse Rejected'), ('EXPIRED_WAREHOUSE_APPROVAL', 'Expired Warehouse Approval'), ('UNDER_REVIEW', 'Under Review'), ('SHARED', 'Shared with Logistics'), ('ACCEPTED', 'Accepted Quote'), ('SHIPMENT_GENERATED', 'Shipment Generated'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=50),
        ),
    ]
