# Generated by Django 4.2.30 on 2026-06-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='fuel_efficiency_rating',
            field=models.DecimalField(decimal_places=2, default=3.0, help_text='Fuel efficiency score (0-5)', max_digits=3),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_image',
            field=models.ImageField(blank=True, help_text='Scanned copy of driving license', null=True, upload_to='licenses/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Driver profile photograph', null=True, upload_to='driver_photos/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Driver performance rating (0-5)', max_digits=3),
        ),
        migrations.AddField(
            model_name='driver',
            name='total_distance_km',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total distance driven in km', max_digits=10),
        ),
        migrations.AddField(
            model_name='driver',
            name='total_trips',
            field=models.PositiveIntegerField(default=0, help_text='Total completed trips'),
        ),
        migrations.AddField(
            model_name='driver',
            name='vahan_verified',
            field=models.BooleanField(default=False, help_text='Whether license has been verified via Vahan API'),
        ),
        migrations.AddField(
            model_name='truck',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Last known latitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Last known longitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='fuel_capacity_liters',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fuel tank capacity in liters', max_digits=8),
        ),
        migrations.AddField(
            model_name='truck',
            name='last_telemetry_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last telemetry update', null=True),
        ),
    ]
