# Generated by Django 4.2.30 on 2026-06-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_driver_fuel_efficiency_rating_driver_license_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='fitness_cert_expiry_date',
            field=models.DateField(blank=True, help_text='Fitness certificate expiry date', null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='insurance_expiry_date',
            field=models.DateField(blank=True, help_text='Insurance policy expiry date', null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='next_service_date',
            field=models.DateField(blank=True, help_text='Next scheduled maintenance date', null=True),
        ),
    ]
