# Generated by Django 4.2.30 on 2026-06-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_truck_fitness_cert_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='employee_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
